theme = "ShowFolio"
languageCode = "en-us"
baseurl = "https://example.com"
title = "Allen Ben Philipose"


[params]
  name = "Allen Hugo - 2"
  description = "Modern portfolio theme for your Hugo site."
  author = "Allen Ben Philipose"
  authorEmail = "allenbphilip@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright © 2021 - Allen Ben Philipose · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Allen"
  tagline = "UX Designer and Product Lead"
  description = "Develop functional user interfaces and provide a valuable experience to customers."
  contact = "https://twitter.com/"


[params.homepage.social]
  instagram = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  github = "https://github.com/"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
